version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - kafka-net
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"  # 开发环境允许匿名访问

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"    # 容器内部通信端口（Docker 网络内访问）
      - "19092:19092"  # 宿主机外部访问端口
    networks:
      - kafka-net
    environment:
      # 注意 bitnami 镜像使用 KAFKA_CFG_ 前缀的配置格式
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:19092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"  # 新增此行
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9093:9093"
    networks:
      - kafka-net
    environment:
      SERVER_PORT: 9093
      KAFKA_CLUSTERS_0_NAME: local-dev
      # 同时配置内部和外部访问地址（UI 展示需要）
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

networks:
  kafka-net:
    driver: bridge